baseURL = "http://harrigan.xyz/"

languageCode        = "en-us"
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa-eh"
author              = "David Harrigan"
title               = "David Harrigan"
pygmentsuseclasses  = true
disqusshortname     = "david_harrigan"
pluralizelisttitles = false
googleAnalytics     = "UA-117782664-1"

[permalinks]
blog  = "blog/:slug/"

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "David Harrigan"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
copyright              = "Copyright © 2018-{year} David Harrigan"
description            = "Don't panic"
email                  = "dave.t.harrigan@gmail.com"      # TODO
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "davidharrigan"
lang                   = "en"
linkedin               = "david-t-harrigan"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
twitter                = "DavidTHarrigan"
instagram              = "david.harrigan"
logofile = "img/me.png"
usesmallsummarycard = true
posts_navigation = true

highlightjs            = true
highlightjslanguages = ["go", "python", "protobuf"]                        # additional languages not included in the "common" set
highlightjsStyle     = "darcula"

avatar                 = "img/me.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
